name: hack
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  server:
    build: .
    environment:
      PORT: 5000
      PGHOST: database
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - "5000:5000"
    depends_on:
      - database
